version: '3'
volumes:
  mongodata:
services:
  mongo:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db

# path: C:\Users\Public\Documents\Hyper-V\Virtual hard disks