settings:
  logging:
    logLevel: 'info'
    isColourize: true
    enableFileLog: true
    fileLogPath: './app.output.log'
    fileLogLevel: 'info'
  serviceAccount:
    username: stevenjiangnz
    password: L@ve@ver77
  serviceBaseUrl: 'http://localhost:8002/' 
  mongoConnection: 'mongodb://localhost:27017/trade_logic_db'
  indicator:
    indicatorsToLoad: 'ema,20|sma,5|sma,10|sma,50|sma,200|bb,20,2.5|adx|macd,26,12,9|heikin|stochastic,14,3|rsi,6|william,14|sma,30|ema,10'
    loadStartDate: 19900101
    loadEndDate: 21000101
  TurningScanSettings: null