settings:
  logging:
    logLevel: 'debug'
    isColourize: true
    enableFileLog: true
    fileLogPath: './app.output.log'
    fileLogLevel: 'info'
  serviceAccount:
    username: stevenjiangnz
    password: L@ve@ver77
  serviceBaseUrl: 'http://localhost:8002/' 
  mongoConnection: 'mongodb://localhost:27017/trade_logic_db'